Select * from customer limit 20 ;

--Q1. What is the total revenue generated by the male vs female customers?
 select gender , sum(purchase_amount) as revenue 
 from customer group by gender;
 
 --Q2. Which customers used a discount bill but still spent more than the average purchase amount? 
 select customer_id, purchase_amount from customer
 where discount_applied='Yes' and purchase_amount >= (select avg(purchase_amount) from customer);
 
 --Q3. Which are the top 5 products with the highest avg review rating ?
 Select item_purchased , ROUND(AVG(review_rating)::numeric, 2) as "Average Product Rating"
 from customer 
 group by item_purchased
 order by avg(review_rating) desc
 limit 5;
 
 --Q4. compare the average purchase amount  between standard and express shipping? 
 select shipping_type, ROUND(avg(purchase_amount)::numeric, 2) from customer where shipping_type in ('Standard','Express')
 group by shipping_type;
 
 --Q5. Do subscribed customer spend more ? compare average spend and total revenue 
 -- between subscriber and non-subscriber
 select subscription_status, COUNT(customer_id) as "Total_Cusotmers",
 ROUND(AVG(purchase_amount)::numeric, 2 ) as "avg_spend",
 ROUND(SUM(purchase_amount)::numeric, 2 ) as "total_revenue"
 from customer group by subscription_status 
 order by total_revenue , avg_spend desc ; 
 
 --Q6. Which 5 product have the highest percentage of purchase with discounts applied?
 select item_purchased, round(100 *SUM(case when discount_applied ='Yes' then 1 else 0 end)/count(*),2) as discount_rate
 from customer 
 group by item_purchased 
 order by discount_rate desc limit 5;
 
 --Q7. Segment customer in the new(1) , returning(10) and loyal(10+) based on their total 
 -- number of previeous purchase , and show the count of each segment 
 with customer_type as (
 select customer_id , previous_purchases, 
case
	when previous_purchases =1 then 'New'
	when previous_purchases between 2 and 10 then 'Returning'
	else'loyal'
	end as customer_segment from customer
	 )
	 select customer_segment , count(*) as "number_of_customer" from customer_type group by customer_segment 
	 order by number_of_customer desc;


--Q8. What are the most purchased top 3 products in the each catogary 
with item_counts as (
select category, item_purchased , count(customer_id) as total_orders,
	row_number() over(partition by category order by count(customer_id) desc) as item_rank from customer
	group by category, item_purchased
)

select item_rank, category, item_purchased, total_orders 
from item_counts where item_rank <= 3 ;

--Q9. are customer those who are repeat buyers(5+) also like to subscribe ? 
select subscription_status, count(customer_id) as repeat_buyers from customer where previous_purchases>5 
group by subscription_status ;

--Q10. what are the revenue contribution of each age grp?
select age_group , sum(purchase_amount) as total_revenue
from customer group by age_group order by total_revenue desc;